services:
  - type: static
    name: my-react-app
    buildCommand: npm install && npm run build
    publishPath: dist
    redirects:
      - source: "/*"
        destination: "/index.html"
        status: 200
